### ISSUE TITLE
Add a Weather Roll Tables to the Compendium or Effect Selector

### ISSUE THREAD

**Issue by Sickma** [LeafWulf/weatherfx#11]
It would be nice if we could get a few roll tables for weather in the different types of climates or a master list to select from.

When I was using the Weather Control module i would have to spam the regenerate weather button in hopes of RNG giving me the  weather effect i wanted to use for my scene. Then i changed to the SmallWeather module to see what it had to offer in terms of weather controls. In my opinion it offered a better layout and i could had more control over what the weather would be like given a region and season, but I was still at the mercy of RNG to get what i wanted. i could use the advance setting for better control, but that would require me to know what the weather was like on a specific day in a specific location.  

Its nice to have all these effects and the chat cards with info on how weather affects the scene, but tedious to re-roll the weather just to get the effects i want, especially when i want to surprise my players with a storm. 
This option could also remove some dependencies on the weather modules and help reduce some of the module bloat/creep that takes up computer resources for features that lags the game for users and for things they may never use.

**Comment by paulo-roger** [comment]
This option is going to be added to smallweather
