### ISSUE TITLE
[[Feature Request]] Scene Exclusion Option

### ISSUE THREAD

**Issue by RinVindor** [LeafWulf/weatherfx#4]
A nice option for the module would be a new check box that doesn't apply weather effects to a scene if said box is checked in that scene's configuration window. Great for the maps you know you'll get lag (like a 16,000 x 16,000 continent map) as well as scenes that are below ground or the like.

**Comment by paulo-roger** [comment]
Good idea! 
Do you have some idea at what image size it usually lags?
We could add a notification warn too when the user has a scene with such image

**Comment by paulo-roger** [comment]
I've added this to the scene config: 
![](https://i.imgur.com/qV6zNzw.png)
