### ISSUE TITLE
Slow down the default speeds of clouds

### ISSUE THREAD

**Issue by apoapostolov** [LeafWulf/weatherfx#7]
This is a quick fix before implementing something more complex like variable speed of winds based on Smallweather.

The current speed of winds is 1. This is very fast for a casual day and could be a good speed for moderate to strong winds day. It is also very distracting for players who want to focus on the map rather than notice moving objects on the map. A good default value for winds would be 0.3 to 0.5, maybe even 0.2.

**Comment by paulo-roger** [comment]
Now the clouds are synced with the wind speed
