### ISSUE TITLE
SmallWeather Wind Speed and Wind Direction

### ISSUE THREAD

**Issue by apoapostolov** [LeafWulf/weatherfx#8]
- Wind speeds should use the descriptor category to set cloud speed, example values below. Values above 3 may be too fast and too compute intensive for WebGL so these are just scalability to test, may be worth to slowly scale and just cap at 3. 

| Calm | 0.05
Light Air 0.1
Light Breeze 0.2
Gentle Breeze 0.35
Moderate Breeze 0.5
Fresh Breeze 0.7
Strong Breeze 1
Near Gale 1.5
Gale 2
Strong Gale 3
Whole Gale 4
Storm Force 5
Hurricane Force 6

* Wind Direction based on the degree passed by weather API. This requires that every canvas has a new setting where DM sets the offset of North that the map uses as North (i.e. North is West, the offset is 270 or -90). The setting may use just an integer field, or a dropdown with "North is..." followed by North/East/South/West/Custom and an integer field to enter custom value. But generally DM should be used to degrees by integer, so enough to just support that.

**Comment by paulo-roger** [comment]
Implemented in the new release :)
